### ISSUE TITLE
I've got problem can't solve 

### ISSUE THREAD

**Issue by kw-yang** [larsyunker/mass-spec-python-tools#14] opened 2019-02-27 09:01 UTC
I'm using Windows 7, python 3.7.1, and what I want to do is to overlay experimental spectrum and theoretical spectrum using 'isotope overlay pattern' module in pythoms script.

I put current directory and spectrum(mzml), and seems nothing wrong to me. But the error occured like this,
Traceback (most recent call last):
  File "L:\Downloads\PythoMS-master\isotope pattern overlay.py", line 240, in <module>
    exp = mzml.sum_scans()
  File "L:\Downloads\PythoMS-master\pythoms\mzml.py", line 1050, in sum_scans
    if self.functions[fn]['type'] != 'MS':
KeyError: 1

I checked mzml.py and maybe [fn] is empty list so keyerror occurs. 

Give me any suggestions. Thanks.

**Comment by larsyunker** [comment] 2019-02-27 17:58
Thanks for bringing this up, I'm hoping that you can provide more details. The script seems to think that there is no mass spectrum in the mzML file, which presumably is not the case. Could you possibly upload the mzML file and the molecular formula of what you're trying to overlay? I will look into it and write a better error catch. Could you also let me know what version of PythoMS you're using? (The version number is in `setup.py` of the root directory)

**Comment by kw-yang** [comment] 2019-02-28 01:29
this is my mzml file,
[A2 new MS2 1406.mzML.gz](https://github.com/larsyunker/PythoMS/files/2912983/A2.new.MS2.1406.mzML.gz)

C71H100N14O16 is molecular formula I'm trying to overlay and I'm using 1.0.3.3 version.
Thank you.

**Comment by larsyunker** [comment] 2019-02-28 17:41
I've found the bug and pushed a fix to the `master` branch. It should work for you now. Please try it out and let me know if the problem is resolved on your side. 

As a side note, it looks like your spectrum is a centroid rather than continuum, which requires setting the `'spectype'` keyword to `'centroid'`. You can uncomment the line in the `override` dictionary in `isotope pattern overlay.py` to enable this. This is the render that I generated, which looks like the match isn't great :( 
![a2 c71h100n14o16](https://user-images.githubusercontent.com/19736507/53586273-a8591e00-3b3c-11e9-927d-5f2ccd0d9aed.png)

**Comment by kw-yang** [comment] 2019-03-04 01:47
It worked well. But the warning occured like
Warning (from warnings module):
  File "C:\Users\HY\AppData\Local\Programs\Python\Python37\lib\site-packages\matplotlib\cbook\__init__.py", line 424
    warn_deprecated("2.2", "Passing one of 'on', 'true', 'off', 'false' as a "
MatplotlibDeprecationWarning: 
Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.

The png file was successfully made, but the warning I encounterd is little bit awkward. 
I think this is python's problem or mistake that I made.

Thanks for fixing error, so now I can use your script. 
Thank you.

**Comment by larsyunker** [comment] 2019-03-04 15:03
I'm glad that it it now fixed. You can safely ignore that warning, it is more of a note to me (the developer) that something has changed in code that I am importing, and that I need to adjust my code to accept it.

**Closed as completed** 2019-03-04 15:03 UTC
Labels: bug

**Comment by kw-yang** [comment] 2019-03-05 06:03
Your comment helped me. Thanks. 
By the way, in isotope pattern overlay.py, I want to use monoisotope[C71H100N14O16+H]+ in simdict but I think this can't recognize. Is there any way to add molecule I want in your script? And also, when I change default "simtype" from bar to gaussian, error like this occured.

Traceback (most recent call last):
  File "L:\yk\Python\pythoms\PythoMS-master\isotope pattern overlay.py", line 253, in <module>
    plot_mass_spectrum(exp, simdict, **keywords)
  File "L:\yk\Python\pythoms\PythoMS-master\pythoms\tome.py", line 788, in plot_mass_spectrum
    simdict[species]['mol'].gaussian_isotope_pattern(simdict[species]['mol'].rawip)
TypeError: 'list' object is not callable

I'm not expert in Python programming, so my question might be annoying to you. Apologize for it.
Thanks.

**Comment by Yeungdb** [comment] 2019-03-05 08:02
Have you tried the request for the monoisotope overlay for C71H101N14O16 versus C71H100N14O16+H from the [M+H] nomenclature? This may assist the molecule class obtain the correct compound in the absence of a + special character.

**Comment by larsyunker** [comment] 2019-03-05 21:33
`IPMolecule` was designed to simulate full isotope patterns, so this wasn't an intended application. I will work on building this functionality in, but in the mean time you could specify isotopes. For example, the formula you are specifying could be simulated with `'H100(12C)71(14N)14(16O)16'`. You can increase the mass by adding `H`'s (e.g. `'H101(12C)71(14N)14(16O)16'`). If you try to specify "+H" this will raise an error. 

The gaussian isotope pattern should now work. There was a missed change from a refactor and has been fixed in #21.

**Comment by kw-yang** [comment] 2019-03-07 06:21
Thanks for comments, and one last thing I want to solve is how can I get only one peak from chromatogram? Like file I attached, there's only one m/z peak for specific time but when I use this script all the peaks from chromatogram came out. 

[A2 new MS2 1406.mzML.gz](https://github.com/larsyunker/PythoMS/files/2939786/A2.new.MS2.1406.mzML.gz)

Thanks.

**Comment by larsyunker** [comment] 2019-03-08 18:10
I'm not sure that I'm understanding what you're trying to do. Are you saying that you want the spectrum from a particular subset of scans in the file? If that's the case, you could use `spectrum binner.py` to bin the scans that you want to sum together, then perform an isotope overlay using the excel file that's generated. 

If that's not what you're trying to do, I will need more details to help you.

**Comment by kw-yang** [comment] 2019-03-11 01:26
Yes, the thing that you suggested is totally what I wanted to do. Sorry for my short English.
I tried to use spectrum binner.py and error like this occured.

  File "L:\Downloads\PythoMS-master\pythoms\mzml.py", line 1050, in sum_scans
    if self.functions[fn]['type'] != 'MS':

KeyError: 1

So I tried to find out what made Keyerror, but I couldn't find it. For testing, I commented out line 1050, 1051 in mzml.py, and error like this occured.

    raise KeyError('The function %d is not in this mzML file.' % fn)

KeyError: 'The function 1 is not in this mzML file.'

I thought it was problem of my .mzml file, so I tried with sample.mzml that you gave in file but it didn't work as well. 

I think that my question is like 'substandard'. Acutually my major is Chemistry so using 'Python' is not familiar to me. Always thanks to you for helping me kindly.

**Comment by larsyunker** [comment] 2019-03-12 18:29
I'm just glad that someone is using the code 😄 . A bug is a bug regardless of who finds it, and you reporting the bug to me helps all future users of the code. I am a chemist by training, and learned Python as a hobby, which is probably why there are so many bugs. 

I have now fixed the bug that was causing these errors (it was the same bug as you first found, I just missed a few usages). Please try that and let me know if it works.

**Comment by kw-yang** [comment] 2019-03-13 01:25
spectrum binner.py now works well but the result is not the thing I want.
Spectrum like I attached(after using spectrum binner.py, plotted by excel) is what I want to get, but it shows same spectrum before using spectrum binner.py
I think I need to sum more spectra. Any suggestion?
Thanks.

![image](https://user-images.githubusercontent.com/48049868/54246860-f37e2280-4579-11e9-8ffc-56eef31e29d6.png)

**Comment by larsyunker** [comment] 2019-03-13 17:20
By default, that script will combine all scans in the mzml file together. You can change that behaviour by specifying the start scan and end scan (lines 66 and 67 respectively in `spectrum binner.py`). With these, you can control which scans are combined, which is what I think you're asking for. You can specify scan number (as an integer) or a time point in minutes (as a float) to narrow the time window.

**Comment by kw-yang** [comment] 2019-03-15 02:42
Finally, I made the plot what I wanted. Now, I need to make some functions like peak library(?), GUI by myself.
Your help totally helped me very well.  Thanks for your kindness. If you don't mind, I'd like to ask you some questions in the future. 

Thanks and best regards, from Korea, 
KW.

**Comment by larsyunker** [comment] 2019-04-24 17:00
HI KW, 
There is now a paper published on this framework, so if you use these tools on data that will be published, I would appreciate it if you could cite [Yunker _et al._ _J. Chem. Inf. Model._, **2019**, _59_(4) pp 1295-1300](https://pubs.acs.org/doi/10.1021/acs.jcim.9b00055).

Thanks!
Lars

**Comment by kw-yang** [comment] 2019-04-26 06:05
OK, I will. Thanks for your contact !

2019년 4월 25일 (목) 오전 2:00, Lars Yunker <notifications@github.com>님이 작성:
